language: python
python:
  - "2.7"
  - "3.4"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

# commands to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
script:
  - nosetests
